### ISSUE TITLE
Why is jaeger empty when opened?

### ISSUE THREAD

**Issue by wajika** [nginxinc/bank-of-sirius#22]
![image](https://user-images.githubusercontent.com/17058349/184054612-f082ff4f-e3a3-4dbb-a967-552f32240cbc.png)
![image](https://user-images.githubusercontent.com/17058349/184054774-c0bcf758-b234-49be-9f38-8a57b95642e9.png)

After I start it through docker-compose up, all services are working fine, but I open the jaeger UI and there is nothing in it, I checked the jaeger log, it seems to be normal.

```
otel-config.yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9978
      http:
        endpoint: 0.0.0.0:9979

  # Collect metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 120s
          static_configs:
            - targets:
              - "balance-reader:8080"
              - "transaction-history:8080"
              - "ledger-writer:8080"
          metrics_path: "/z/prometheus"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    logLevel: debug

  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

  extensions: [health_check, pprof, zpages]
```
